version: '3.8'

services:
  web:
    build: .
    container_name: time_keeper
    ports:
      - "5000:5000"
    volumes:
      # Mount instance directory for database persistence
      - ./instance:/app/instance
      # Mount app code for development (comment out for production)
      - ./app:/app/app
      - ./run.py:/app/run.py
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///instance/development.db
    restart: unless-stopped
